### ISSUE TITLE
A docker container to clean up your docker containers

### ISSUE THREAD

**Issue by crohr** [crohr/ebarnouflant#1]
If you don't use the `--rm` flag when launching docker containers (and even if you do), your disks are going to slowly but surely fill up with all the cached layers and unused images. People usually schedule [docker-cleanup-volumes](https://github.com/chadoe/docker-cleanup-volumes) in a cron to counter this, but now you can also just run a docker image that does it for you:

```
docker run \
  --restart \
  -e KEEP_IMAGES="ubuntu:14.04 corp/important-image:tag" \
  -v /var/run/docker.sock:/var/run/docker.sock:rw \
  -v /var/lib/docker:/var/lib/docker:rw \
  meltwater/docker-cleanup:latest
```

See the [relevant repo](https://github.com/meltwater/docker-cleanup) for more details and a systemd init script.

**Comment by mikljohansson** [comment]
Might want to adjust the example to include a restart-policy for the `--restart` parameters, e.g. `--restart=on-failure` to avoid docker failing to start

Cheers, 
 Mikael

**Comment by crohr** [comment]
@mikljohansson thanks for the catch, corrected!

**Comment by joshughes** [comment]
https://github.com/spotify/docker-gc

**Comment by crohr** [comment]
@joshughes Thanks for that, didn't know about it! Do you know if it also makes sure to delete unused volume directories? In the past I've often seen that deleting the exited containers and unused images still left a lot of GB behind because of those.

**Comment by joshughes** [comment]
@crohr So we are using docker 1.6.2 because we have some hurdles to upgrade. That release has a known issue where volumes are not always cleaned up correctly. Docker-GC does not do anything specifically with volumes. It finds and deletes dead containers and unused images very very well though. We run it in production to keep our servers happy! 

https://github.com/chadoe/docker-cleanup-volumes  My team has contemplated giving this a go to help with the task of cleaning up those orphaned volumes. Currently docker-gc is running in a cron job and we would run this in a cron as well... although probably just nightly vs the fact that we run docker-gc every 15 minutes. 

I can speak to the fact that docker-gc is rock solid and helped us a lot, but I have not had time to really see what docker-cleanup-volumes can do.
